name: New library version
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  FORCE_COLOR: 3

jobs:
  generate_tag:
    timeout-minutes: 2
    #  && github.event.pull_request.merged == true
    if: github.event.repository.full_name == github.repository
    name: Generate a new patch version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config --global user.email "robotito@legendaryum.com"
          git config --global user.name "botito"
      - name: Generate tag
        run:
          bash ./scripts/generate-tag.sh
