name: release

on:
  push:
    branches:
      - main
    tags:
    # only patch versions
      - 'v0.1.*'

permissions:
  contents: write
  # packages: write
  # issues: write


env:
  FORCE_COLOR: 3
  GO_VERSION: 1.22
defaults:
  run:
    shell: bash

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
